name: Run Test Workflow
run-name: Running test workflow
on: push
jobs:
    Run-Test-Workflow:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm run test